### PR TITLE
Remove from GitHub

### PR DESCRIPTION
**Pull request by NovaAndrom3da**

### CODE REVIEW

**Review by TheEssem — CHANGES_REQUESTED** [review]
Seems like this only removes the README at the moment; it'll be much more helpful to remove the rest of the files.

**Review by TheEssem — APPROVED** [review]
Never mind, I saw it wrong.

**Comment by NovaAndrom3da** [comment]
If you need help merging these changes into your fork of Firefox-Onebar, you can run these easy commands:

```
cd Firefox-Onebar
rm -rf *
git reset efc4fc2
git commit -m 'Remove from GitHub'
git push --force
```

**Comment by NovaAndrom3da** [comment]
@silvanshade What are you even doing lmao

**Pull request closed without merging**
